name: yumemi_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed: ^2.5.2
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  go_router: ^14.0.2
  dio: ^5.4.3+1
  infinite_scroll_pagination: ^4.0.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  github_language_colors: ^1.0.1
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/images/launcher/android_bg.png"
  adaptive_icon_foreground: "assets/images/launcher/android_fg.png"

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
