name: flutter-ci

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test
      - run: flutter build apk
